<?php

namespace AppBundle\Repository;
use Doctrine\ORM\QueryBuilder;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;

/**
 * AbstractRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
abstract class AbstractRepository extends \Doctrine\ORM\EntityRepository
{
    protected function paginate(QueryBuilder $queryBuilder, $limit = 20, $offset = 0)
    {


        if(0 == $limit)
        {
            throw new \LogicException('$limit & $offstet must be greater than 0.');
        }
        $pager = new Pagerfanta(new DoctrineORMAdapter($queryBuilder));
        $currentPage = ceil(($offset+1)/$limit);
        $pager->setCurrentPage($currentPage);
        $pager->setMaxPerPage((int)$limit);
        return $pager;
    }
}
