<?php

namespace AppBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends AbstractRepository
{
    public function search($term, $order = "asc", $limit = 20, $offset = 0)
    {
        $qb = $this->createQueryBuilder('a')->select('a')->orderBy('a.title',$order);
        if($term)
        {
            $qb->where($qb->expr()->like('a.title','%'.$term.'%'));
        }
        return $this->paginate($qb,$limit,$offset);
    }
}
